// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceDemografi.Models;

namespace Service.Demografi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ServiceDemografi.Models.Demografi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Agama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Desa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Golongan_Darah")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jenis_Kelamin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kecamatan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kelurahan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kewarganegaraan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodePos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Masa_Berlaku")
                        .HasColumnType("datetime2");

                    b.Property<long>("NIK")
                        .HasColumnType("bigint");

                    b.Property<string>("Nama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pekerjaan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Provinsi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RW")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusPerkawinan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tanggal_Lahir")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tempat_Lahir")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Demografis");
                });

            modelBuilder.Entity("ServiceDemografi.Models.PhotoID", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DemografiId")
                        .HasColumnType("int");

                    b.Property<long>("NIK")
                        .HasColumnType("bigint");

                    b.Property<string>("Path_Photo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DemografiId");

                    b.ToTable("PhotoIDs");
                });

            modelBuilder.Entity("ServiceDemografi.Models.PhotoID", b =>
                {
                    b.HasOne("ServiceDemografi.Models.Demografi", "Demografi")
                        .WithMany("PhotoIDs")
                        .HasForeignKey("DemografiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
